name: 🐛 Bug Report
description: Create a report to help us improve PyFolio C++
title: "[Bug]: "
labels: ["bug", "triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! 
        
        Before submitting, please check if a similar issue already exists.

  - type: input
    id: version
    attributes:
      label: PyFolio C++ Version
      description: What version of PyFolio C++ are you using?
      placeholder: "v1.0.0"
    validations:
      required: true

  - type: dropdown
    id: environment
    attributes:
      label: Environment
      description: What environment are you running PyFolio C++ in?
      options:
        - Linux (Ubuntu/Debian)
        - Linux (CentOS/RHEL)
        - Linux (Other)
        - macOS (Intel)
        - macOS (Apple Silicon)
        - Windows 10
        - Windows 11
        - Docker Container
        - Kubernetes Cluster
        - Other
    validations:
      required: true

  - type: dropdown
    id: compiler
    attributes:
      label: Compiler
      description: Which compiler are you using?
      options:
        - GCC 11
        - GCC 12
        - GCC 13
        - Clang 14
        - Clang 15
        - Clang 16
        - MSVC 2019
        - MSVC 2022
        - Other
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
      placeholder: Describe the issue you're experiencing...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: Describe what you expected to happen...
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened?
      placeholder: Describe what actually happened...
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Provide a minimal example to reproduce the issue
      placeholder: |
        1. Initialize portfolio with...
        2. Call function...
        3. See error...
      render: text
    validations:
      required: true

  - type: textarea
    id: code
    attributes:
      label: Minimal Code Example
      description: If applicable, provide a minimal code example that reproduces the issue
      render: cpp
      placeholder: |
        #include <pyfolio/core/portfolio.h>
        
        int main() {
            // Your minimal reproducing code here
            return 0;
        }

  - type: textarea
    id: logs
    attributes:
      label: Error Messages/Logs
      description: Copy and paste any relevant error messages or log output
      render: text
      placeholder: Paste error messages here...

  - type: textarea
    id: config
    attributes:
      label: Build Configuration
      description: Provide your CMake configuration and build commands
      render: bash
      placeholder: |
        cmake -DCMAKE_BUILD_TYPE=Release -DBUILD_TESTS=ON ..
        make -j$(nproc)

  - type: checkboxes
    id: checklist
    attributes:
      label: Additional Information
      options:
        - label: I have searched for existing issues
          required: true
        - label: I am using the latest version
          required: false
        - label: I can consistently reproduce the issue
          required: false
        - label: The issue occurs with minimal example code
          required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context about the problem here (dependencies, system specs, etc.)
      placeholder: Any additional information...